#!/usr/bin/env python3
prefix_postfix_separators = ["", ".", "-", "_"]

prefixes_postfixes = [
    # 'administration',
    # 'administrator',
    # 'ansible',
    # 'api',
    # 'aws',
    # 'aws-logs',
    # 'awscloudtrail',
    # 'awslogs',
    # 'betas',
    # 'billing',
    # 'bucket',
    # 'bugbounty',
    # 'bugs',
    # 'certs',
    # 'cloud',
    # 'cloudtrail',
    # 'club',
    # 'clubs',
    # 'cluster',
    # 'clusters',
    # 'cms',
    # 'com',
    # 'company',
    # 'confidential',
    # 'consumer',
    # 'contact',
    # 'content',
    # 'contracts',
    # 'corporate',
    # 'data-export',
    # 'data-exports',
    # 'dataset',
    # 'datasets',
    # 'design',
    # 'dev-files',
    # 'developer',
    # 'developers',
    # 'development',
    # 'devops',
    # 'documents',
    # 'elasticsearch',
    # 'email-assets',
    # 'engineer',
    # 'engineering',
    # 'fiannces',
    # 'finance',
    # 'financial',
    # 'general',
    # 'intranet',
    # 'kafka',
    # 'kbfiles',
    # 'kerberos',
    # 'key',
    # 'keys',
    # 'kibana',
    # 'linux',
    # 'loadbalancer',
    # 'logexport',
    # 'logos',
    # 'logstash',
    # 'mac',
    # 'marketing',
    # 'matrix',
    # 'maven',
    # 'media',
    # 'member',
    # 'members',
    # 'mobile',
    # 'mongo',
    # 'mongodb',
    # 'operations',
    # 'ops',
    # 'partners',
    # 'password',
    # 'passwords',
    # 'photos',
    # 'pics',
    # 'prod',
    # 'production',
    # 'products',
    # 'project',
    # 'projects',
    # 'public',
    # 'reports',
    # 'research',
    # 's3',
    # 'software',
    # 'splunk',
    # 'ssl',
    # 'static',
    # 'static-files',
    # 'subversion',
    # 'support',
    # 'support-attachments',
    # 'supportdocs',
    # 'supportmedia',
    # 'supportuploads',
    # 'tls',
    # 'ui',
    # 'ui-staging',
    # 'user',
    # 'user-files',
    # 'users',
    # 'ux',
    # 'web',
    # 'web-assets',
    # 'web-data',
    # 'web-gstatic',
    # 'web-static',
    # 'webassets',
    # 'webdata',
    # 'website',
    # 'website-assets',
    # 'websiteassets',
    # 'webstatic',
    # 'windows',
    # 'www-assets',
    'admin',
    'archive',
    'assets',
    'attachments',
    'backup',
    'backups',
    'bak',
    'beta',
    'cdn',
    'data',
    'database',
    'databases',
    'db',
    'dbs',
    'dev',
    'download',
    'downloads',
    'dump',
    'dumps',
    'export',
    'exports',
    'files',
    'git',
    'github',
    'internal',
    'sql',
    'staging',
    'temp',
    'tmp',
    'upload',
    'uploads',
]